server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html;
    index index.html;

    include /etc/nginx/mime.types;
    types {
        application/javascript js;
        application/json json lh ls atlas;
        application/octet-stream sk shader;
        audio/mpeg mp3;
        audio/wav wav;
        image/png png;
        image/jpeg jpg jpeg;
        image/webp webp;
        image/x-icon ico;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }

    location ~* \.(js|json|png|jpg|jpeg|webp|mp3|wav|lh|ls|atlas|sk|shader)$ {
        try_files $uri =404;
        expires 30d;
        add_header Cache-Control "public";
    }
}
